# Generated by Django 4.1.7 on 2023-03-17 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('topic', models.CharField(choices=[('Romantic Relationships', 'Romantic Relationships'), ('Family/Friends', 'Family/Friends'), ('Recreation/Hobbies', 'Recreation/Hobbies'), ('Work', 'Work'), ('Identity/Appearance', 'Identity/Appearance'), ('Food', 'Food'), ('Environmental Issues', 'Environmental Issues'), ('Technology', 'Technology'), ('History', 'History'), ('Politics/Government', 'Politics/Government'), ('Sports', 'Sports'), ('Health', 'Health'), ('Transportation', 'Transportation'), ('Arts/Entertainment/Media', 'Arts/Entertainment/Media'), ('Values', 'Values')], max_length=24)),
                ('content', models.TextField(max_length=2500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
