# Generated by Django 4.1.7 on 2023-03-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_author_comment_article_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='owner',
        ),
    ]
